### ISSUE TITLE
Plugin not working with Abaqus 6.14

### ISSUE THREAD

**Issue by waelzaki** [smrg-uob/PeriodicBoundaryCondition#1]
When trying to run the plugin in Abaqus 6.14-3, the following error log is produced:

Traceback (most recent call last):
  File "c:/SIMULIA/Abaqus/6.14-3/code/python2.7/lib/abaqus_plugins/PeriodicBCs\PeriodicBoundaryCondition_plugin.py", line 149, in getNextDialog
    return self.get_next_dialog()
  File "c:/SIMULIA/Abaqus/6.14-3/code/python2.7/lib/abaqus_plugins/PeriodicBCs\PeriodicBoundaryCondition_plugin.py", line 37, in get_next_dialog
    return self.get_input_dialog()
  File "c:/SIMULIA/Abaqus/6.14-3/code/python2.7/lib/abaqus_plugins/PeriodicBCs\PeriodicBoundaryCondition_plugin.py", line 49, in get_input_dialog
    return PeriodicBoundaryCondition_DB.InputDialog(self, self.STEP_NEW)
  File "c:/SIMULIA/Abaqus/6.14-3/code/python2.7/lib/abaqus_plugins/PeriodicBCs\PeriodicBoundaryCondition_DB.py", line 328, in __init__
    self.on_model_selected()
  File "c:/SIMULIA/Abaqus/6.14-3/code/python2.7/lib/abaqus_plugins/PeriodicBCs\PeriodicBoundaryCondition_DB.py", line 393, in on_model_selected
    reset_combo_box(self.cbx_part, mdb.models[models[model_index]].parts.keys())
TypeError: list indices must be integers, not NoneType

**Comment by xvheule** [comment]
The plugin was developed for ABAQUS CAE 2018, use with prior versions was not foreseen, my apologies.
