### ISSUE TITLE
Code does not work with orphaned mesh.

### ISSUE THREAD

**Issue by LumiaSLS** [smrg-uob/PeriodicBoundaryCondition#3]
Hi,

the node pairing process ended with the following error if two surfaces created from a part with only orphaned mesh are used in the plug-in: 

Traceback (most recent call last):
  File "c:/SIMULIA/CAE/2019/win_b64/code/python2.7/lib/abaqus_plugins/abaqus_plugins\PeriodicBoundaryCondition_plugin.py", line 177, in doCustomChecks
    self.issue_pair()
  File "c:/SIMULIA/CAE/2019/win_b64/code/python2.7/lib/abaqus_plugins/abaqus_plugins\PeriodicBoundaryCondition_plugin.py", line 105, in issue_pair
    issue_command(cmd)
  File "c:/SIMULIA/CAE/2019/win_b64/code/python2.7/lib/abaqus_plugins/abaqus_plugins\PeriodicBoundaryCondition_plugin.py", line 229, in issue_command
    abaqusGui.sendCommand(cmd.getCommandString())
  File "SMAPyaModules\SMAPyaAbqPy.m\src\sendcmd.py", line 35, in sendCommand
KeyError: 'f2ccz const radius R2-1'

The same model with natively created mesh (same mesh) in Abaqus works with no problem.

thanks!

**Comment by xvheule** [comment]
I haven't used orphaned meshes before so not quite sure what could be done.
But indeed, the code not working on oprhaned meshes is not surprising given the fact that it uses the parts to find the mesh.

Possible work arounds:
 - Create a dummy part containing the mesh, it is unclear to me why or what the benefits of an orphaned mesh are tough.
 - Generate the constraints first, and then orphan the mesh? Again, I have no experience with this so I am not sure this might work.
 - Adapt the python code.
