### ISSUE TITLE
KeyError when pairing

### ISSUE THREAD

**Issue by graphitical** [smrg-uob/PeriodicBoundaryCondition#6]
I am getting a KeyError while trying to pair my surfaces for Abaqus 2020.
All other aspects of the PBC are valid/true.
P632 is the part name and it is all one solid body.

**Model** with surfaces to be matched in red
![image](https://user-images.githubusercontent.com/15367628/161333412-fe004bc9-4886-46f5-818c-a4ecd0347cf6.png)

**Window**

![image](https://user-images.githubusercontent.com/15367628/161333252-90b448ee-ec11-4cd2-a708-dbeaf0a1ef59.png)

**Log** 
> Traceback (most recent call last):
  File "c:/SIMULIA/CAE/plugins/2020/PeriodicBoundaryCondition/PeriodicBoundaryCondition\PeriodicBoundaryCondition_plugin.py", line 177, in doCustomChecks
    self.issue_pair()
  File "c:/SIMULIA/CAE/plugins/2020/PeriodicBoundaryCondition/PeriodicBoundaryCondition\PeriodicBoundaryCondition_plugin.py", line 105, in issue_pair
    issue_command(cmd)
  File "c:/SIMULIA/CAE/plugins/2020/PeriodicBoundaryCondition/PeriodicBoundaryCondition\PeriodicBoundaryCondition_plugin.py", line 229, in issue_command
    abaqusGui.sendCommand(cmd.getCommandString())
  File "SMAPyaModules\SMAPyaAbqPy.m\src\sendcmd.py", line 36, in sendCommand
KeyError: 'P632-1'

**Comment by graphitical** [comment]
Upon rebuilding the file and surfaces the error has gone away. Unclear why, but at least it is working now. Thank you for your help.
